model:
  hidden_layers: [256, 128]
  learning_rate: 0.001
  batch_size: 32
  epochs: 100

environment:
  control_freq: 100
  horizon: 500
  ignore_done: True

evaluation:
  metrics: ["collision_rate", "smoothness", "accuracy"]
